trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  CI: true

steps:
- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm ci'

- script: |
    npm run test
  displayName: 'npm test'

- script: |
    npm run build
  displayName: 'npm build'